export const RS_QUESTIONS = [
  "The university library has an extensive collection of academic journals and research papers.",
  "Students are required to submit their assignments before the deadline to avoid penalties.",
  "The professor explained the concept of supply and demand during the economics lecture.",
  "Climate change is one of the most significant challenges facing the world today.",
  "The research findings suggest a strong correlation between diet and overall health.",
  "International students must demonstrate English proficiency before enrolling in the program.",
  "The lecture will cover the fundamental principles of modern physics and quantum mechanics.",
  "Students who participate in group discussions tend to develop better communication skills.",
  "The government has announced new funding for renewable energy research and development.",
  "Effective time management is essential for achieving academic success at the university level.",
  "The laboratory experiment demonstrated the chemical reaction between hydrogen and oxygen.",
  "Artificial intelligence is transforming the way businesses operate across multiple industries.",
  "The scholarship program provides financial assistance to students from disadvantaged backgrounds.",
  "Regular physical exercise has been proven to improve both mental and physical well being.",
  "The campus bookstore offers a wide range of textbooks and academic reference materials.",
  "Environmental sustainability should be integrated into all aspects of urban planning and development.",
  "The seminar focused on the latest developments in biotechnology and genetic engineering.",
  "Critical thinking skills are highly valued by employers in the modern competitive job market.",
  "The museum exhibition showcases artifacts from ancient civilizations around the Mediterranean region.",
  "Digital technology has revolutionized the way people access information and communicate globally.",
  "The student council organized a charity event to raise funds for the local community.",
  "Agricultural practices must evolve to meet the food demands of a growing global population.",
  "The conference brought together experts from various fields to discuss innovative solutions.",
  "Public transportation systems play a vital role in reducing urban congestion and pollution.",
  "The research paper examined the effects of social media on adolescent mental health patterns.",
  "Universities are increasingly offering online courses to accommodate diverse learning preferences.",
  "The architectural design of the building reflects both modern aesthetics and environmental consciousness.",
  "Statistical analysis is a fundamental tool used in scientific research across many disciplines.",
  "The orientation program helps new students familiarize themselves with campus resources and services.",
  "Global trade agreements have significant implications for economic development in emerging markets.",
  "The documentary explored the impact of deforestation on biodiversity in tropical rainforest regions.",
  "Students are encouraged to seek guidance from academic advisors when selecting their course schedules.",
  "The health clinic provides free vaccinations and medical consultations to all registered students.",
  "Technological innovation drives economic growth and creates new employment opportunities worldwide.",
  "The philosophy department offers courses ranging from ancient Greek thought to contemporary ethics.",
  "Water conservation strategies are essential for ensuring sustainable access to clean drinking water.",
  "The graduation ceremony will be held in the main auditorium on the last day of term.",
  "Collaborative learning environments promote knowledge sharing and enhance problem solving abilities.",
  "The economic forecast predicts moderate growth in the manufacturing sector over the next quarter.",
  "Peer review is an essential component of the academic publishing and research validation process.",
  "The engineering faculty recently received a grant for developing sustainable building materials.",
  "Cultural diversity enriches the educational experience and prepares students for a globalized world.",
  "The biology course includes both theoretical lectures and practical laboratory sessions each week.",
  "Effective leadership requires strong communication skills and the ability to motivate team members.",
  "The university has established partnerships with several international research institutions worldwide.",
  "Renewable energy sources are becoming increasingly cost competitive with traditional fossil fuels.",
  "The psychology experiment investigated how environmental factors influence human decision making processes.",
  "Academic integrity is a fundamental principle that all students must uphold throughout their studies.",
  "The transportation network connects the university campus to major residential areas in the city.",
  "Scientific literacy enables citizens to make informed decisions about health and environmental issues.",
  "The financial aid office assists students in applying for grants and low interest education loans.",
  "Modern telecommunications technology has dramatically reduced the cost of international communication.",
  "The history department is hosting a symposium on the political revolutions of the twentieth century.",
  "Nutritional education programs help individuals make healthier food choices for long term wellness.",
  "The research methodology course teaches students how to design and conduct rigorous academic studies.",
  "Urban green spaces contribute to improved air quality and enhanced mental well being for residents.",
  "The international exchange program allows students to spend a semester studying at partner universities.",
  "Data privacy regulations are becoming increasingly important in the digital information age we live in.",
  "The medical school curriculum emphasizes both clinical practice and biomedical research fundamentals.",
  "Sustainable development requires balancing economic growth with environmental protection and social equity.",
  "The campus recreation center offers fitness classes and sports facilities for all enrolled students.",
  "Machine learning algorithms can analyze large datasets to identify patterns and predict future outcomes.",
  "The admissions committee evaluates applicants based on academic achievement and extracurricular involvement.",
  "Biodiversity conservation is essential for maintaining healthy ecosystems and supporting human well being.",
  "The writing center provides tutoring services to help students improve their academic writing skills.",
  "International cooperation is necessary for addressing global challenges such as climate change effectively.",
  "The physics laboratory is equipped with advanced instruments for conducting precision measurements.",
  "Social entrepreneurship combines business principles with a commitment to creating positive social impact.",
  "The career services department helps graduates prepare for job interviews and professional networking events.",
  "Evidence based medicine relies on systematic research to guide clinical decision making in healthcare.",
  "The astronomy course covers topics from planetary science to the formation of distant galaxy clusters.",
  "Educational technology continues to evolve and create new opportunities for personalized student learning.",
  "The environmental science program includes fieldwork components in various ecological research settings.",
  "Democratic governance requires an informed citizenry that actively participates in the political process.",
  "The student accommodation office assists international students in finding suitable housing arrangements.",
  "Cognitive development in children is influenced by both genetic factors and environmental experiences.",
  "The law school clinic provides free legal advice to members of the surrounding local community.",
  "Nanotechnology research is opening new possibilities in medicine and materials science applications.",
  "The academic calendar includes designated periods for examinations and independent study and revision.",
  "Cross cultural communication skills are increasingly important in today's interconnected global workplace.",
  "The chemistry department recently published groundbreaking research on catalytic reaction mechanisms.",
  "Mental health awareness campaigns aim to reduce stigma and encourage individuals to seek professional help.",
  "The university press publishes scholarly works across a wide range of academic disciplines and fields.",
  "Precision agriculture uses technology to optimize crop yields while minimizing environmental impact overall.",
  "The student government association represents undergraduate interests in university policy making decisions.",
  "Geothermal energy provides a reliable and sustainable alternative to conventional power generation methods.",
  "The linguistics program explores how languages develop and change across different cultures over time.",
  "Early childhood education has lasting effects on cognitive development and future academic achievement.",
  "The research ethics committee reviews all proposed studies involving human participants before approval.",
  "Globalization has increased economic interdependence among nations and transformed international trade patterns.",
  "The performing arts center hosts regular concerts and theatrical productions throughout the academic year.",
  "Immunization programs have significantly reduced the prevalence of infectious diseases in developed countries.",
  "The graduate school offers master and doctoral programs in over thirty different academic disciplines.",
  "Coastal erosion threatens infrastructure and communities in many low lying areas around the world today.",
  "The information technology department maintains the university network and provides technical support services.",
  "Comparative education research examines how different countries approach curriculum design and teacher training.",
  "The sports science program combines exercise physiology with nutrition and performance psychology studies.",
  "Electoral reform is necessary to ensure fair representation and strengthen democratic institutions worldwide.",
  "The student wellness center offers counseling services and stress management workshops throughout the semester.",
  "Advances in robotics are creating new applications in healthcare and manufacturing and space exploration.",
  "The anthropology museum contains artifacts collected from archaeological excavations conducted over many decades.",
  "Public health initiatives focus on disease prevention and health promotion at the community population level.",
  "The mathematics department offers tutoring sessions to support students enrolled in introductory calculus courses.",
  "Diplomatic negotiations require patience and cultural sensitivity and a willingness to find common ground.",
  "The journalism program emphasizes ethical reporting practices and multimedia storytelling techniques.",
  "Ocean acidification poses a significant threat to marine ecosystems and the species that depend on them.",
  "The continuing education division provides professional development courses for working adults and career changers.",
  "Behavioral economics examines how psychological factors influence economic decision making in real world contexts.",
  "The campus security team ensures the safety of students and staff through regular patrols and monitoring.",
  "Stem cell research holds promise for developing new treatments for a wide range of medical conditions.",
  "The political science department offers courses on international relations and comparative government systems.",
  "Food security remains a critical challenge in many developing regions affected by conflict and climate change.",
  "The alumni association organizes networking events and mentorship programs for current and former students.",
  "Quantum computing has the potential to solve complex problems that are beyond classical computing capabilities.",
  "The occupational therapy program trains students to help patients recover functional independence after injury.",
  "Urbanization is increasing rapidly in developing countries and creating new challenges for city planners.",
  "The digital humanities center supports interdisciplinary research using computational methods and tools.",
  "Vaccination hesitancy has become a public health concern requiring targeted education and communication efforts.",
  "The engineering workshop provides hands on training in computer aided design and manufacturing processes.",
  "Emotional intelligence plays an important role in building effective professional relationships in the workplace.",
  "The geography department uses geographic information systems to analyze spatial patterns and environmental data.",
  "Microplastic pollution in the oceans is an emerging environmental threat requiring urgent scientific attention.",
  "The study abroad office coordinates exchange programs with partner institutions in over twenty countries.",
  "Renewable energy investment has increased significantly over the past decade driven by falling technology costs.",
  "The veterinary school provides clinical training through its on campus animal hospital and community outreach.",
  "Space exploration continues to expand our understanding of the universe and inspire future scientific discoveries.",
  "The disability services office ensures that all students have equal access to educational resources and facilities.",
  "Artificial neural networks are designed to simulate the way biological brains process and learn from information.",
  "The sociology department examines how social structures and cultural norms influence individual behavior patterns.",
  "Coral reef degradation threatens marine biodiversity and the livelihoods of coastal communities around the world.",
  "The music conservatory offers instruction in classical performance and jazz improvisation and music composition.",
  "Telemedicine has expanded access to healthcare services particularly in rural and underserved geographic areas.",
  "The honors program provides academically gifted students with enhanced research opportunities and smaller classes.",
  "Carbon capture technology aims to reduce greenhouse gas emissions from industrial processes and power generation.",
  "The education faculty conducts research on effective teaching methodologies and student assessment practices.",
  "Wildlife conservation efforts require collaboration between governments and communities and international organizations.",
  "The pharmacy school curriculum includes extensive coursework in pharmacology and pharmaceutical chemistry.",
  "Autonomous vehicle technology is expected to transform transportation and reduce traffic accidents significantly.",
  "The art gallery showcases works by both established artists and emerging talents from the local creative community.",
  "Epidemiological studies help identify risk factors for diseases and guide public health intervention strategies.",
  "The business incubator supports student entrepreneurs in developing and launching innovative startup ventures.",
  "Genetic testing can provide valuable information about an individual predisposition to certain hereditary conditions.",
  "The marine biology station conducts research on coastal ecosystems and the effects of pollution on marine life.",
  "Universal access to quality education is recognized as a fundamental human right by international organizations.",
  "The nuclear physics laboratory conducts experiments to investigate the fundamental structure of matter and energy.",
  "Climate adaptation strategies are essential for helping vulnerable communities prepare for environmental changes.",
  "The dental school provides affordable oral healthcare services to patients from the surrounding local community.",
  "Blockchain technology has applications beyond cryptocurrency including supply chain management and digital identity.",
  "The theater department produces several major stage productions each academic year featuring student performers.",
  "Antibiotic resistance is a growing global health threat that requires coordinated international response efforts.",
  "The cooperative education program integrates academic study with practical work experience in professional settings.",
  "Three dimensional printing technology is being used to create prototypes and customized medical devices efficiently.",
  "The public policy institute analyzes government programs and recommends evidence based reforms for social improvement.",
  "Wetland preservation is critical for maintaining water quality and providing habitat for diverse wildlife species.",
  "The nursing school emphasizes patient centered care and evidence based clinical practice in all training programs.",
  "Virtual reality applications are expanding beyond entertainment into education and healthcare and job training.",
  "The agricultural research station develops improved crop varieties adapted to local growing conditions and climates.",
  "Interpersonal communication skills are essential for success in both academic and professional environments today.",
  "The forensic science program trains students in evidence collection and analysis for criminal justice applications.",
  "Sustainable fishing practices are necessary to prevent overharvesting and protect marine ecosystem health globally.",
  "The learning management system allows instructors to distribute materials and track student progress electronically.",
  "Gene therapy research is advancing rapidly and offering new hope for patients with previously untreatable conditions.",
  "The architecture studio emphasizes sustainable design principles and innovative approaches to urban space planning.",
  "International humanitarian law establishes rules for the conduct of armed conflict and protection of civilian populations.",
  "The recreation department organizes outdoor adventure trips and wellness activities for the entire campus community.",
  "Precision medicine tailors treatment approaches to individual patient characteristics based on genetic and clinical data.",
  "The social work program prepares students for careers in community development and mental health counseling services.",
  "Circular economy principles promote resource efficiency by designing products for reuse and recycling from the start.",
  "The planetarium hosts educational shows about astronomy and space science for students and community members alike.",
  "Neuroplasticity research demonstrates that the human brain can reorganize and form new neural connections throughout life.",
  "The translation studies program trains students in professional translation and cross cultural communication techniques.",
  "Drought resistant crop varieties are being developed to help farmers adapt to changing precipitation patterns worldwide.",
  "The volunteer center connects students with community service opportunities that complement their academic interests.",
  "Wearable health monitoring devices can track vital signs and alert users to potential medical issues in real time.",
  "The industrial design program combines artistic creativity with engineering principles to create functional products.",
  "Restorative justice practices focus on repairing harm and rebuilding relationships rather than purely punitive measures.",
  "The aquatic research center studies freshwater ecosystems and develops strategies for sustainable water resource management.",
  "Digital citizenship education teaches students about responsible and ethical behavior in online environments today.",
  "The materials science laboratory investigates the properties and applications of advanced polymers and composite structures.",
  "Early intervention programs for children with developmental delays can significantly improve long term learning outcomes.",
  "The energy management office implements efficiency measures to reduce the university carbon footprint and operating costs.",
  "Comparative literature courses examine texts from different cultures and explore universal themes in human storytelling.",
  "The speech pathology clinic provides assessment and treatment services for individuals with communication disorders.",
  "Regenerative medicine research aims to develop biological therapies that can repair or replace damaged tissues and organs.",
  "The community engagement office coordinates partnerships between the university and local nonprofit service organizations.",
  "Autonomous drone technology is being applied in agriculture and environmental monitoring and emergency response operations.",
  "The conflict resolution center offers mediation services and teaches negotiation skills to students and community members."
];